<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jquery.simplemodal.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jquery.colorpicker.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/agenda.js'); ?>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery("#agenda").agenda({
			getagendatableUrl:'<?=$this->baseUrl?>/json/getagendatable/location/<?=$this->currentLocation->userid?>/currentdate/<?=$this->date?>/',
			getmodalcontentUrl:'<?=$this->baseUrl?>/json/getmodalcontent/',
			gettimeendUrl:'<?=$this->baseUrl?>/json/gettimeend/',
			customerId:'<?=isset ( $this->currentCustomer ) ? $this->currentCustomer->userid : ''?>',
			locationId:'<?=$this->currentLocation->userid?>',
			currentDate:'<?=$this->date?>',
			imagesDir:'<?=$this->baseUrl?>/images/'
		});
	});

    $(function(){
        $.datepicker.setDefaults({
            dateFormat: 'yy-mm-dd',
            yearRange: "-100:+0",
        });
        $('#dp').datepicker({
            changeMonth: true,
            changeYear: true,
            onSelect: function(selectedDate) {
                location.replace("<?=$this->baseUrl?>/location/index/id/<?=$this->currentLocation->userid?>/date/"+selectedDate+"/");
            }
        });
        $("#selectDate").click(function() {
            $("#dp").datepicker("show");
            return false;
        });
    });

	function appointmentOtherClick(locationId) {
		location.replace("<?=$this->baseUrl?>/location/index/id/"+locationId+"/date/<?=$this->date?>/");		
	}
</script>

<div id="editAppointment" class="edit_appointment"></div>

<h2 style="margin-bottom: 0;">Agenda <?=htmlentities ( $this->currentLocation->bedrijfsnaam )?></h2>
<?php
$first = true;
foreach ( $this->locationsToShow as $location ) {
	?>
	<?=$first ? $first = false : ' | '?><?=$location->userid == $this->currentLocation->userid ? '' : '<a	href="' . $this->baseUrl . '/location/index/id/' . $location->userid . '/date/' . $this->date . '/">'?><?=htmlentities ( $location->bedrijfsnaam )?><?=$location->userid == $this->currentLocation->userid ? '' : '</a>'?>
	<?php
	$first = false;
}
?>
<br />
<h3 style="margin-bottom: 0;"><?=htmlentities ( ucfirst ( ($this->dateToPrint->get ( 'EEEE d MMMM yyyy', 'nl_NL' )) ) )?></h3>
<a
	href="<?=$this->baseUrl?>/location/index/id/<?=$this->currentLocation->userid?>/date/<?=$this->monthSubtract?>/"><<</a>
maand
<a
	href="<?=$this->baseUrl?>/location/index/id/<?=$this->currentLocation->userid?>/date/<?=$this->monthAdd?>/">>></a>
<a
	href="<?=$this->baseUrl?>/location/index/id/<?=$this->currentLocation->userid?>/date/<?=$this->weekSubtract?>/"><<</a>
week
<a
	href="<?=$this->baseUrl?>/location/index/id/<?=$this->currentLocation->userid?>/date/<?=$this->weekAdd?>/">>></a>
<a
	href="<?=$this->baseUrl?>/location/index/id/<?=$this->currentLocation->userid?>/date/<?=$this->daySubtract?>/"><<</a>
dag
<a
	href="<?=$this->baseUrl?>/location/index/id/<?=$this->currentLocation->userid?>/date/<?=$this->dayAdd?>/">>></a>
<a id="selectDate" href="#">kies datum</a><input type="hidden" id="dp" />
|
<a
	href="<?=$this->baseUrl?>/location/index/id/<?=$this->currentLocation->userid?>/">vandaag</a>
<br />
<br />

<table id="agenda" class="scroll" cellpadding="0" cellspacing="0"></table>

<br />
<br />
