<link rel="stylesheet" type="text/css" media="screen"
	href="<?=$this->baseUrl?>/css/jqGrid/jqModal.css" />
<link rel="stylesheet"
	href="<?=$this->baseUrl?>/css/jqDatePicker/datePicker.css"
	type="text/css" />

<script src="<?=$this->baseUrl?>/scripts/js/jqModal.js"
	type="text/javascript"></script>
<script src="<?=$this->baseUrl?>/scripts/js/jqDnR.js"
	type="text/javascript"></script>
<script type="text/javascript" src="<?=$this->baseUrl?>/scripts/date.js"></script>
<script type="text/javascript"
	src="<?=$this->baseUrl?>/scripts/jquery.datePicker.js"></script>
