<script type="text/javascript">
	jQuery(document).ready(function(){
	jQuery("#list").jqGrid({
		url:'<?=$this->baseUrl?>/json/employeessetup/',
		datatype: "json",
		colNames:['Naam', ''],
		colModel:[
		  		{name:'name',index:'name',width:240},
		  		{width:40,sortable:false}		  		
		],
		rowNum:10,
		imgpath: '<?=$this->baseUrl?>/images/jqGrid',
		mtype: "POST",		
		pager: jQuery('#pager'),
		sortname: 'id',
		viewrecords: true,
		sortorder: "asc",
		multiselect: false, 		
		width: 280,
		height: "auto"
	});
	});

	/////////////////////
	// Products search //
	/////////////////////
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var name = jQuery("#name").val();
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/employeessetup/?name="+name,page:1
		}).trigger("reloadGrid");
	}
</script>

<h2>Medewerkers</h2>

<table class="list left" width="280">
	<tr class="noborder">
		<td>Naam</td>
	</tr>
	<tr class="noborder">
		<td><input type="text" name="name" id="name" style="width: 150px;"
			onkeydown="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>
<br />
<!-- Add employee form stond uit. Met een reden? -->
<form action="<?=$this->baseUrl?>/admin/employeeadd/"><input
	type="submit" value="Add employee" /></form>
<br />
<br />
