<script type="text/javascript">
	jQuery(document).ready(function(){
	jQuery("#list").jqGrid({
		url:'<?=$this->baseUrl?>/json/groups/',
		datatype: "json",
		colNames:['Naam', ''],
		colModel:[
		  		{name:'name',index:'name',width: 710},
		  		{width: 50, sortable:false}		  		
		],
		rowNum:10,
		imgpath: '<?=$this->baseUrl?>/images/jqGrid',
		mtype: "POST",		
		pager: jQuery('#pager'),
		sortname: 'id',
		viewrecords: true,
		sortorder: "asc",
		multiselect: false, 		
		width: 760,
		height: "auto"
	});
	});

	/////////////////////
	// News search //
	/////////////////////
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var name = jQuery("#name").val();
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/groups/?name="+name,page:1
		}).trigger("reloadGrid");
	}
</script>

<h2>Groepen</h2>

<table class="list left" style="width: 735px">
	<tr class="noborder">
		<td>Naam</td>
	</tr>
	<tr class="noborder">
		<td><input type="text" name="name" id="name" style="width: 250px;"
			onkeydown="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>
<br />

<form action="<?=$this->baseUrl?>/admin/groupadd/" method="post"><input
	type="text" name="name" style="width: 250px;" /> <input type="submit"
	value="Nieuwe groep" /></form>

<br />
<br />