<script type="text/javascript">
	jQuery(document).ready(function(){
	jQuery("#list").jqGrid({
		url:'<?=$this->baseUrl?>/json/invoicessearch/',
		datatype: "json",
		colNames:['Datum', 'Klant', 'Medewerker', 'Vestiging', 'Prijs', 'Type', ''],
		colModel:[
		  		{name:'date',index:'date'},
		  		{name:'customer',index:'customer'},
		  		{name:'employee',index:'employee'},		  		
		  		{name:'location',index:'location'},
		  		{name:'totalwithoutreduction',index:'totalwithoutreduction'},
		  		{name:'paymentmethod',index:'paymentmethod'},
		  		{name:'buttons',sortable:false}		  		
		],
		rowNum:10,
		imgpath: '<?=$this->baseUrl?>/images/jqGrid',
		mtype: "POST",		
		pager: jQuery('#pager'),
		sortname: 'id',
		viewrecords: true,
		sortorder: "desc",
		multiselect: false,
		width: 760,
		height: "auto"
	});
	});
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var employee_id = jQuery("#filter_employee").val();
		var location_id = jQuery("#filter_location").val();
		var paymentmethod = jQuery("#filter_paymentmethod").val();
		var date_start = jQuery("#filter_date_start").val();
		var date_end = jQuery("#filter_date_end").val();
		var price_start = jQuery("#filter_price_start").val();
		var price_end = jQuery("#filter_price_end").val();
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/invoicessearch/?employee_id="+employee_id+"&location_id="+location_id+"&paymentmethod="+paymentmethod+"&date_start="+date_start+"&date_end="+date_end+"&price_start="+price_start+"&price_end="+price_end,page:1
		}).trigger("reloadGrid");
	}
	
	Date.format = 'dd-mm-yyyy';
	$(function(){
		$('#filter_date_start').datePicker({startDate:'01/01/1900', createButton:false, clickInput:true});
		$('#filter_date_start').dpSetOffset(20, 0);
		$('#filter_date_end').datePicker({startDate:'01/01/1900', createButton:false, clickInput:true});
		$('#filter_date_end').dpSetOffset(20, 0);
	});
</script>

<h2>Rekeningen</h2>

<table id="search">
	<tr class="noborder">
		<td>Medewerker:</td>
		<td><select name="filter_employee" id="filter_employee"
			style="width: 160px;" onchange="doSearch(arguments[0]||event)">
			<option></option>
			<?php
			foreach ( $this->filterEmployees as $employee ) {
				?>
			<option value="<?=$employee->id?>"><?=htmlentities ( $employee->name )?></option>
			<?php
			}
			?>			
		</select></td>
		<td></td>
		<td>Van</td>
		<td>Tot en met</td>
	</tr>
	<tr>
		<td>Vestiging:</td>
		<td><select name="filter_location" id="filter_location"
			style="width: 160px;" onchange="doSearch(arguments[0]||event)">
			<option></option>
			<?php
			foreach ( $this->filterLocations as $location ) {
				?>
			<option value="<?=$location->userid?>"><?=htmlentities ( $location->bedrijfsnaam )?></option>
			<?php
			}
			?>			
		</select></td>
		<td>Datum:</td>
		<td><input type="text" name="filter_date_start" id="filter_date_start"
			style="width: 110px;" onkeydown="doSearch(arguments[0]||event)"
			onchange="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="filter_date_end" id="filter_date_end"
			style="width: 110px;" onkeydown="doSearch(arguments[0]||event)"
			onchange="doSearch(arguments[0]||event)" /></td>
	</tr>
	<tr>
		<td>Betaalwijze:</td>
		<td><select name="filter_paymentmethod" id="filter_paymentmethod"
			style="width: 160px;" onchange="doSearch(arguments[0]||event)">
			<option></option>
			<option value="kas">Kas</option>
			<option value="bank">Bank</option>
			<option value="pin">Pin</option>
		</select></td>
		<td>Prijs &#0128;:</td>
		<td><input type="text" name="filter_price_start"
			id="filter_price_start" style="width: 110px;"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="filter_price_end" id="filter_price_end"
			style="width: 110px;" onkeydown="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>
