<script type="text/javascript">
	jQuery(document).ready(function(){
	jQuery("#list").jqGrid({
		url:'<?=$this->baseUrl?>/json/locationssetup/',
		datatype: "json",
		colNames:['Naam', 'Adres 1', 'Adres 2', 'Woonplaats', 'Postcode', 'E-mail', ''],
		colModel:[
		  		{name:'name',index:'name', width:150},
		  		{name:'deliveryaddress1',index:'deliveryaddress1', width:150},
		  		{name:'deliveryaddress2',index:'deliveryaddress2', width:150},		  		
		  		{name:'city',index:'city', width:100},
		  		{name:'zip',index:'zip', width:100},
		  		{name:'email',index:'email', width:150},
		  		{width:40,sortable:false}		  		
		],
		rowNum:10,
		imgpath: '<?=$this->baseUrl?>/images/jqGrid',
		mtype: "POST",		
		pager: jQuery('#pager'),
		sortname: 'id',
		viewrecords: true,
		sortorder: "asc",
		multiselect: false, 		
		width: 760,
		height: "auto"
	});
	});

	/////////////////////
	// Products search //
	/////////////////////
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var name = jQuery("#name").val();
		var deliveryaddress1 = jQuery("#deliveryaddress1").val();		
		var deliveryaddress2 = jQuery("#deliveryaddress2").val();		
		var city = jQuery("#city").val();
		var zip = jQuery("#zip").val();
		var email = jQuery("#email").val();		
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/locationssetup/?name="+name+"&deliveryaddress1="+deliveryaddress1+"&deliveryaddress2="+deliveryaddress2+"&city="+city+"&zip="+zip+"&email="+email,page:1
		}).trigger("reloadGrid");
	}
</script>

<h2>Locaties</h2>

<table class="list left" width="100%">
	<tr class="noborder">
		<td>Naam:</td>
		<td><input type="text" name="name" id="name"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td>Adres 1:</td>
		<td><input type="text" name="deliveryaddress1" id="deliveryaddress1"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td>Adres 2:</td>
		<td><input type="text" name="deliveryaddress2" id="deliveryaddress2"
			onkeydown="doSearch(arguments[0]||event)"
			onchange="doSearch(arguments[0]||event)" /></td>
	</tr>
	<tr class="noborder">
		<td>Woonplaats:</td>
		<td><input type="text" name="city" id="city"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td>Postcode:</td>
		<td><input type="text" name="zip" id="zip"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td>E-mail:</td>
		<td><input type="text" name="email" id="email"
			onkeydown="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>
<br />

<form action="<?=$this->baseUrl?>/admin/locationadd/"><input
	type="submit" value="Add location" /></form>

<br />
<br />