<h2>Add location</h2>
<p>
	<?php
	if (isset ( $this->messages ['username'] )) {
		foreach ( $this->messages ['username'] as $message ) {
			?><span class="errorMessage"><b>Naam:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	if (isset ( $this->messages ['password'] )) {
		foreach ( $this->messages ['password'] as $message ) {
			?><span class="errorMessage"><b>Wachtwoord:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	if (isset ( $this->messages ['deliveryaddress1'] )) {
		foreach ( $this->messages ['deliveryaddress1'] as $message ) {
			?><span class="errorMessage"><b>Adres 1:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	if (isset ( $this->messages ['deliveryaddress2'] )) {
		foreach ( $this->messages ['deliveryaddress2'] as $message ) {
			?><span class="errorMessage"><b>Adres 2:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	if (isset ( $this->messages ['city'] )) {
		foreach ( $this->messages ['city'] as $message ) {
			?><span class="errorMessage"><b>Woonplaats:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	if (isset ( $this->messages ['zip'] )) {
		foreach ( $this->messages ['zip'] as $message ) {
			?><span class="errorMessage"><b>Postcode:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	if (isset ( $this->messages ['email'] )) {
		foreach ( $this->messages ['email'] as $message ) {
			?><span class="errorMessage"><b>E-mail:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	?>
</p>

<form method="post">
<table class="medium">
	<tr>
		<th colspan="2">Locatie login</th>
	</tr>
	<tr>
		<td>Naam:</td>
		<td><input type="text" name="username"
			value="<?=isset ( $this->user->username ) ? htmlentities ( $this->user->username ) : ''?>" /></td>
	</tr>
	<tr>
		<td>Wachtwoord:</td>
		<td><input type="text" name="password"
			value="<?=isset ( $this->user->password ) ? htmlentities ( $this->user->password ) : ''?>" /></td>
	</tr>
	<tr>
		<td>Actief:</td>
		<td><input type="checkbox" name="state" value="1" <?=$this->user->state ? 'checked' : ''?>" /></td>
	</tr>
	<tr>
		<th colspan="2">Adres</th>
	</tr>
	<tr>
		<td>Adres 1:</td>
		<td><input type="text" name="deliveryaddress1"
			value="<?=isset ( $this->locationToEdit->deliveryaddress1 ) ? htmlentities ( $this->locationToEdit->deliveryaddress1 ) : ''?>" /></td>
	</tr>
	<tr>
		<td>Adres 2:</td>
		<td><input type="text" name="deliveryaddress2"
			value="<?=isset ( $this->locationToEdit->deliveryaddress2 ) ? htmlentities ( $this->locationToEdit->deliveryaddress2 ) : ''?>" /></td>
	</tr>
	<tr>
		<td>Woonplaats:</td>
		<td><input type="text" name="city"
			value="<?=isset ( $this->locationToEdit->city ) ? htmlentities ( $this->locationToEdit->city ) : ''?>" /></td>
	</tr>
	<tr>
		<td>Postcode:</td>
		<td><input type="text" name="zip"
			value="<?=isset ( $this->locationToEdit->zip ) ? htmlentities ( $this->locationToEdit->zip ) : ''?>" /></td>
	</tr>
	<tr>
		<td>E-mail:</td>
		<td><input type="text" name="email"
			value="<?=isset ( $this->locationToEdit->email ) ? htmlentities ( $this->locationToEdit->email ) : ''?>" /></td>
	</tr>
	<tr>
		<th colspan="2">Medewerkers</th>
	</tr>
	<tr>
		<td colspan="2">
			<?php
			foreach ( $this->employeesToShow as $employee ) {
				?>
			<input type="checkbox" name="employee_locations[]"
			value="<?=$employee->id?>"
			<?=in_array ( $employee->id, $this->employee_locations ) ? 'checked' : ''?> /> <?=htmlentities ( $employee->name )?><br />
			<?php
			}
			?>
		</td>
	</tr>
</table>
<br />
<input type="submit" value="OK" /></form>
<form action="<?=$this->baseUrl?>/admin/locations/"><input type="submit"
	value="Back" /></form>