<script type="text/javascript">
function checkAll() {
	var fldName = 'cb';
	var f = document.newsForm;
	var c = f.toggle.checked;
	for (i=0; i < n; i++) {
		cb = eval( 'f.' + fldName + '' + i );
		if (cb) {
			cb.checked = c;
		}
	}
}

var n=<?php
echo count ( $this->news );
?>;
</script>

<h2>Nieuwsbrief - Stap 1 - Selecteer bericht</h2>
<form method="post" action="<?=$this->baseUrl?>/admin/newsletter2/"
	name="newsForm">
<table class="notes" style="width: 100%">
	<tr>
		<th><input type="checkbox" name="toggle" value=""
			onclick="checkAll();" /></th>
		<th width="100%">Onderwerp</th>
		<th>Datum</th>
		<th>Actief</th>
	</tr>
	<?php
	$i = 0;
	foreach ( $this->news as $newsItem ) {
		?>
	<tr>
		<td><input type="checkbox" id="cb<?php
		echo $i;
		?>" name="ids[]"
			value="<?php
		echo $newsItem->id;
		?>" /></td>
		<td><?=$this->escape ( $newsItem->title )?></td>
		<td><nobr><?=$this->escape ( $newsItem->date )?></nobr></td>
		<td style="text-align: center;"><?=($newsItem->published ? 'Ja' : 'Nee')?></td>
	</tr>
	<?php
		$i ++;
	}
	?>
	<tr>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
</table>
<br />
<input type="submit" value="Stap 2 &gt;" /></form>