<h2>Bestellen details</h2>
<form method="post">
<table class="notes">
	<tr>
		<td>Header</td>
		<td><textarea name="header"><?=htmlentities ( $this->orderdetailsRow->header )?></textarea></td>
	</tr>
	<tr>
		<td>Voetnoot</td>
		<td><textarea name="footer"><?=htmlentities ( $this->orderdetailsRow->footer )?></textarea></td>
	</tr>
	<tr>
		<td></td>
		<td>

</table>
<br />
<input type="submit" value="OK" /></form>