<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/i18n/grid.locale-nl.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jquery.jqGrid.min.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jqModal.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jqDnR.js'); ?>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#list").jqGrid({
            url:'<?=$this->baseUrl?>/json/productstop/',
            datatype: "json",
            colModel:[
                {label: 'Code', name:'productcode',index:'productcode', sortable:false, width: 65},
                {label: 'Product', name:'name',index:'name', sortable:false, width: 120},
                {label: 'Aantal', name:'number_total',index:'number_total', sortable:false, width: 60},		  		
                {label: ' ', sortable:false, width: 20},
                {label: 'Verkoopprijs', name:'total_price_total',index:'total_price_total', sortable:false, width: 100, align:"right"}
            ],
            viewrecords: true,
            width: 380,
            height: "auto",
            rowNum: 10,
            pager: '#pager',
            mtype: "POST",
            sortname: 'id',
            sortorder: "asc",
            multiselect: false
        });
	});
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var filter_employee = jQuery("#filter_employee").val();
		var filter_location = jQuery("#filter_location").val();
		var filter_date_start = jQuery("#filter_date_start").val();
		var filter_date_end = jQuery("#filter_date_end").val();
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/productstop/?filter_employee="+filter_employee+"&filter_location="+filter_location+"&filter_date_start="+filter_date_start+"&filter_date_end="+filter_date_end,page:1
		}).trigger("reloadGrid");
	}

	$(function(){
        $.datepicker.setDefaults({
            dateFormat: 'dd-mm-yy',
            yearRange: "-100:+0",
        });
        $('#filter_date_start').datepicker({changeMonth: true, changeYear: true});
        $('#filter_date_end').datepicker({changeMonth: true, changeYear: true});
	});
</script>

<h2>Producten Top</h2>

<form>
<table>
	<tr class="noborder">
		<td>Medewerker:</td>
		<td><select name="filter_employee" id="filter_employee"
			style="width: 160px;" onchange="doSearch(arguments[0]||event)">
			<option></option>
			<?php
			foreach ( $this->filterEmployees as $employee ) {
				?>
			<option value="<?=$employee->id?>"
				<?=$this->input->filter_employee == $employee->id ? 'selected' : ''?>><?=htmlentities ( $employee->name )?></option>
			<?php
			}
			?>			
		</select></td>
		<td></td>
		<td>Van</td>
		<td>Tot en met</td>
	</tr>
	<tr>
		<td>Vestiging:</td>
		<td><select name="filter_location" id="filter_location"
			style="width: 160px;" onchange="doSearch(arguments[0]||event)">
			<option></option>
			<?php
			foreach ( $this->filterLocations as $location ) {
				?>
			<option value="<?=$location->userid?>"
				<?=$this->input->filter_location == $location->userid ? 'selected' : ''?>><?=htmlentities ( $location->bedrijfsnaam )?></option>
			<?php
			}
			?>			
		</select></td>
		<td>Datum:</td>
		<td><input type="text" name="filter_date_start" id="filter_date_start"
			value="<?=$this->input->filter_date_start ? $this->printDate->filter ( $this->input->filter_date_start ) : ''?>"
			style="width: 110px;" onkeydown="doSearch(arguments[0]||event)"
			onchange="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="filter_date_end" id="filter_date_end"
			value="<?=$this->input->filter_date_end ? $this->printDate->filter ( $this->input->filter_date_end ) : ''?>"
			style="width: 110px;" onkeydown="doSearch(arguments[0]||event)"
			onchange="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
</form>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>

<br />
<br />
