<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/i18n/grid.locale-nl.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jquery.jqGrid.min.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jqModal.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jqDnR.js'); ?>
<script type="text/javascript">
	jQuery(document).ready(function(){
        jQuery("#list").jqGrid({
            url:'<?=$this->baseUrl?>/json/productssetup/',
            datatype: "json",
            colModel:[
                {label: 'Code', name:'productcode',index:'productcode', width:140},
                {label: 'Product', name:'name',index:'name', width:200},
                {label: 'Categorie', name:'category',index:'category', width:110},		  		
                {label: 'Inhoud', name:'size',index:'size', width:110},
                {label: ' ', width:20,sortable:false},		  		
                {label: 'Prijs', name:'price',index:'price', width:80, align:"right"},
                {label: 'Leverancier', name:'supplier',index:'supplier', width:120},
                {label: ' ', width:40,sortable:false}
            ],
            viewrecords: true,
            width: 780,
            height: "auto",
            rowNum: 10,
            pager: '#pager',
            mtype: "POST",
            sortname: 'id',
            sortorder: "asc",
            multiselect: false
        });
	});

	/////////////////////
	// Products search //
	/////////////////////
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var productcode = jQuery("#productcode").val();
		var name = jQuery("#name").val();
		var category = jQuery("#category").val();
		var size = jQuery("#size").val();
		var price = jQuery("#price").val();		
		var supplier = jQuery("#supplier").val();		
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/productssetup/?productcode="+productcode+"&name="+name+"&category="+category+"&size="+size+"&price="+price+"&supplier="+supplier,page:1
		}).trigger("reloadGrid");
	}
</script>

<h2>Producten</h2>

<table class="list left" style="width: 735px">
	<tr class="noborder">
		<td>Code</td>
		<td>Product</td>
		<td>Type</td>
		<td>Size</td>
		<td>Price</td>
		<td>Supplier</td>
	</tr>
	<tr class="noborder">
		<td><input type="text" name="productcode" id="productcode"
			style="width: 90px;" onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="name" id="name" style="width: 150px;"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="category" id="category"
			style="width: 75px;" onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="size" id="size" style="width: 75px;"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="price" id="price" style="width: 75px;"
			class="number" onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="supplier" id="supplier"
			style="width: 75px;" onkeydown="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>
<br />

<form action="<?=$this->baseUrl?>/admin/productadd/"><input
	type="submit" value="Add product" /></form>

<br />
<br />