<h2>Verkoop</h2>

<table>
	<tr class="noborder">
		<td><b>Medewerker:</b></td>
		<td><?=(isset ( $this->filter_employee ) ? $this->escape ( $this->filter_employee ) : '')?></td>
		<td></td>
		<td><b>Van</b></td>
		<td><b>Tot en met</b></td>
	</tr>
	<tr>
		<td><b>Vestiging:</b></td>
		<td><?=(isset ( $this->filter_location ) ? $this->escape ( $this->filter_location ) : '')?></td>
		<td><b>Datum:</b></td>
		<td><?=$this->input->filter_date_start ? $this->printDate->filter ( $this->input->filter_date_start ) : ''?></td>
		<td><?=$this->input->filter_date_end ? $this->printDate->filter ( $this->input->filter_date_end ) : ''?></td>
	</tr>
	<tr>
		<td><b>Betaalwijze:</b></td>
		<td><?=$this->input->filter_paymentmethod?></td>
		<td><b>Prijs &#0128;:</b></td>
		<td><?=$this->input->filter_price_start ? $this->printPrice->filter ( $this->input->filter_price_start ) : ''?></td>
		<td><?=$this->input->filter_price_end ? $this->printPrice->filter ( $this->input->filter_price_end ) : ''?></td>
	</tr>
</table>

<br />

<table class="list autowidth">
	<tr class="left">
		<th>Categorie</th>
		<th colspan="3">Verkoopwaarde</th>
		<th colspan="3">Korting</th>
		<th colspan="3">Verkoop&nbsp;inc.BTW</th>
		<th colspan="3">Verkoop&nbsp;ex.BTW</th>
		<th colspan="3">BTW&nbsp;laag</th>
		<th colspan="3">BTW&nbsp;hoog</th>
	</tr>
	<?php
	$total = 0;
	$reduction = 0;
	$withVat = 0;
	$withoutVat = 0;
	$vatHigh = 0;
	$vatLow = 0;
	$i = true;
	foreach ( $this->lines as $line ) {
		?>
	<tr class="<?=$i ? 'dark' : 'light'?> left">
		<td><?=htmlentities ( $line->name ? $line->name : 'No category' )?></td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $line->total ) )?></td>
		<td></td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $line->reduction ) )?></td>
		<td></td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $line->total - $line->reduction ) )?></td>
		<td></td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $line->total - $line->reduction - $line->vat_high - $line->vat_low ) )?></td>
		<td>&nbsp;&nbsp;</td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $line->vat_low ) )?></td>
		<td></td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $line->vat_high ) )?></td>
		<td></td>
	</tr>
	<?php
		$total += $line->total;
		$reduction += $line->reduction;
		$withVat += $line->total - $line->reduction;
		$withoutVat += $line->total - $line->reduction - $line->vat_high - $line->vat_low;
		$vatHigh += $line->vat_high;
		$vatLow += $line->vat_low;
		$i = ! $i;
	}
	?>
	<tr class="noborder">
		<td colspan="19">&nbsp;</td>
	</tr>
	<tr class="dark left">
		<td><b>Totaal</b></td>
		<td>&#0128;</td>
		<td class="right"><b><?=htmlentities ( $this->printPrice->filter ( $total ) )?></b></td>
		<td>&nbsp;&nbsp;</td>
		<td>&#0128;</td>
		<td class="right"><b><?=htmlentities ( $this->printPrice->filter ( $reduction ) )?></b></td>
		<td></td>
		<td>&#0128;</td>
		<td class="right"><b><?=htmlentities ( $this->printPrice->filter ( $withVat ) )?></b></td>
		<td></td>
		<td>&#0128;</td>
		<td class="right"><b><?=htmlentities ( $this->printPrice->filter ( $withoutVat ) )?></b></td>
		<td>&nbsp;&nbsp;</td>
		<td>&#0128;</td>
		<td class="right"><b><?=htmlentities ( $this->printPrice->filter ( $vatLow ) )?></b></td>
		<td>&nbsp;&nbsp;</td>
		<td>&#0128;</td>
		<td class="right"><b><?=htmlentities ( $this->printPrice->filter ( $vatHigh ) )?></b></td>
		<td>&nbsp;&nbsp;</td>
	</tr>
</table>

<br>
<br>
<table class="list medium" style="width: 280px;">
	<tr class="light">
		<th width="100%">Totalen</th>
		<th colspan="3">Bedrag</th>
	</tr>
	<tr class="light">
		<td>Producten</td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $this->products ) )?></td>
		<td>&nbsp;&nbsp;</td>
	</tr>
	<tr class="light">
		<td>Behandelingen</td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $this->consults ) )?></td>
		<td>&nbsp;&nbsp;</td>
	</tr>
	<tr class="dark">
		<td><b>Totaal</b></td>
		<td>&#0128;</td>
		<td class="right"><b><?=htmlentities ( $this->printPrice->filter ( $this->products + $this->consults ) )?></b></td>
		<td>&nbsp;&nbsp;</td>
	</tr>
	<tr class="">
		<td colspan="4">&nbsp;</td>
	</tr>
	<tr class="light">
		<td>Kas</td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $this->cash ) )?></td>
		<td></td>
	</tr>
	<tr class="light">
		<td>Pin</td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $this->pin ) )?></td>
		<td></td>
	</tr>
	<tr class="light">
		<td>Op rekening</td>
		<td>&#0128;</td>
		<td class="right"><?=htmlentities ( $this->printPrice->filter ( $this->invoice ) )?></td>
		<td></td>
	</tr>
	<tr class="dark">
		<td><b>Totaal</b></td>
		<td>&#0128;</td>
		<td class="right"><b><?=htmlentities ( $this->printPrice->filter ( $this->cash + $this->pin + $this->invoice ) )?></b></td>
		<td></td>
	</tr>
</table>
<br />



