<h2>Edit adres</h2>
<p>
	<?php
	if (isset ( $this->messages ['email'] )) {
		foreach ( $this->messages ['email'] as $message ) {
			?><span class="errorMessage"><b>Email:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	if (isset ( $this->messages ['active'] )) {
		foreach ( $this->messages ['active'] as $message ) {
			?><span class="errorMessage"><b>Active:</b>:&nbsp;<?=$message?></span><br /><?php
		}
	}
	?>
</p>

<form method="post">
<table class="notes">
	<tr>
		<td>Naam:</td>
		<td></td>
		<td><input type="text" name="name"
			value="<?=isset ( $this->testsubscriber->name ) ? $this->escape ( $this->testsubscriber->name ) : ''?>" /></td>
	</tr>
	<tr>
		<td>Groep:</td>
		<td></td>
		<td><select name="group_id">
			<option value="0">&nbsp;</option>
			<?php
			foreach ( $this->groups as $group ) {
				?>
			<option value="<?=$group->id?>"
				<?=isset ( $this->testsubscriber->group_id ) && $this->testsubscriber->group_id == $group->id ? 'selected' : ''?>><?=$this->escape ( $group->name )?></option>
			<?php
			}
			?>
		</select></td>
	</tr>
	<tr>
		<td>Email:</td>
		<td></td>
		<td><input type="text" name="email" id="email"
			value="<?=isset ( $this->testsubscriber->email ) ? $this->escape ( $this->testsubscriber->email ) : ''?>" /></td>
	</tr>
	<tr>
		<td>Actief:</td>
		<td></td>
		<td><input type="radio" name="active" id="active" value="1"
			<?=$this->testsubscriber->active == 1 ? 'checked="checked"' : ''?> />
		Ja <input type="radio" name="active" id="active" value="0"
			<?=$this->testsubscriber->active != 1 ? 'checked="checked"' : ''?> />
		Nee</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
	</tr>
</table>
<br />
<input type="submit" value="OK" /></form>
<form
	action="<?=$this->baseUrl?>/admin/groupedit/id/<?php
	echo $this->testsubscriber->group_id?>/"><input type="submit"
	value="Terug" /></form>