<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/i18n/grid.locale-nl.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jquery.jqGrid.min.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jqModal.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl . '/scripts/jqDnR.js'); ?>
<script type="text/javascript">
	jQuery(document).ready(function(){
        jQuery("#list").jqGrid({
            url:'<?=$this->baseUrl?>/json/supplierssetup/',
            datatype: "json",
            colModel:[
                {label: 'Naam', name:'name',index:'name',width:120},
                {label: 'E-mail', name:'email',index:'email',width:120},
                {label: ' ', width:40,sortable:false}
            ],
            viewrecords: true,
            width: 280,
            height: "auto",
            rowNum: 10,
            pager: '#pager',
            mtype: "POST",
            sortname: 'id',
            sortorder: "asc",
            multiselect: false
        });
	});

	/////////////////////
	// Products search //
	/////////////////////
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var name = jQuery("#name").val();
		var email = jQuery("#email").val();
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/supplierssetup/?name="+name+"&email="+email,page:1
		}).trigger("reloadGrid");
	}
</script>

<h2>Leveranciers</h2>

<table class="list left" width="280">
	<tr class="noborder">
		<td>Naam</td>
		<td>E-mail</td>
	</tr>
	<tr class="noborder">
		<td><input type="text" name="name" id="name" style="width: 100px;"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="email" id="email" style="width: 150px;"
			onkeydown="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>
<br />

<form action="<?=$this->baseUrl?>/admin/supplieradd/"><input
	type="submit" value="Add supplier" /></form>

<br />
<br />