<script type="text/javascript">
	jQuery(document).ready(function(){
	jQuery("#list").jqGrid({
		url:'<?=$this->baseUrl?>/json/testsubscribers/',
		datatype: "json",
		colNames:['Naam', 'Email', 'Actief', ''],
		colModel:[
		  		{name:'name',index:'name', width: 400},
		  		{name:'email',index:'email', width: 150},
		  		{name:'active',index:'active', width: 150},
		  		{width: 60, sortable:false}		  		
		],
		rowNum:10,
		imgpath: '<?=$this->baseUrl?>/images/jqGrid',
		mtype: "POST",		
		pager: jQuery('#pager'),
		sortname: 'id',
		viewrecords: true,
		sortorder: "asc",
		multiselect: false, 		
		width: 760,
		height: "auto"
	});
	});

	/////////////////////
	// News search //
	/////////////////////
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var name = jQuery("#name").val();
		var email = jQuery("#email").val();
		var active = jQuery("#active").val();
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/testsubscribers/?name="+name+"&email="+email+"&active="+active,page:1
		}).trigger("reloadGrid");
	}
</script>

<h2>Test adressen</h2>

<table class="list left" style="width: 735px">
	<tr class="noborder">
		<td>Naam</td>
		<td>Email</td>
		<td>Actief</td>
	</tr>
	<tr class="noborder">
		<td style="width: 405px;"><input type="text" name="name" id="name"
			style="width: 250px;" onkeydown="doSearch(arguments[0]||event)" /></td>
		<td style="width: 150px;"><input type="text" name="email" id="email"
			style="width: 90px;" onkeydown="doSearch(arguments[0]||event)"
			onchange="doSearch(arguments[0]||event)" /></td>
		<td style="width: 180px;"><select name="active" id="active"
			onchange="doSearch(arguments[0]||event)">
			<option></option>
			<option value="1">Ja</option>
			<option value="0">Nee</option>
		</select></td>
	</tr>
</table>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>
<br />

<form action="<?=$this->baseUrl?>/admin/testsubscriberadd/"><input
	type="submit" value="Voeg test adres toe" /></form>

<br />
<br />