<link rel="stylesheet"
	href="<?=$this->baseUrl?>/css/jqDatePicker/datePicker.css"
	type="text/css" />
<link rel="stylesheet" type="text/css" media="screen"
	href="<?=$this->baseUrl?>/css/jqGrowl/jgrowl.css" />

<script type="text/javascript" src="<?=$this->baseUrl?>/scripts/date.js"></script>
<script type="text/javascript"
	src="<?=$this->baseUrl?>/scripts/jquery.datePicker.js"></script>
<script type="text/javascript"
	src="<?=$this->baseUrl?>/scripts/jquery.jgrowl.js"></script>
