<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?= $this->headTitle('NewDiet Care')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/jqGrid/grid.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Head Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('scripts/jquery.jqGrid.js'))
            ->prependFile($this->basePath('scripts/jquery.js'))
        ?>
    </head>
    <body>
        <div id="container">
			<div id="header">
				<div id="logo">
					<h1>NewDiet Care</h1>
				</div>
				<div id="info">
					<div class="customer">
						<table>
							<tr class="noborder">
								<th colspan=3 class="left">
									<h4><?= isset ( $this->currentCustomer ) ? $this->escapeHtml( $this->currentCustomer->getName () ) : '' ?></h4>
								</th>
								<th class="space"></th>
								<td class="wide right" style="border-bottom: 1px solid #97aed0; font-weight: bold;">
									<a href="<?= $this->url('customer', ['action' => 'index']) ?>">Kies&nbsp;klant</a>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
        	<div id="menu">
				<?php
					$menu = $this->navigation('Zend\Navigation\Default')->menu();
					$menu->setUlClass('')->setLiActiveClass('selected');
					if ( ! isset( $this->location ) ) {
						$menu->findOneBy( 'label', 'Klant' )->removePage( $menu->findOneBy( 'label', 'Afrekenen' ) );
					}
					echo $menu;
				?>
        	</div>
        	<div id="content">
            	<?= $this->content; ?>
        	</div>
        </div>
        <!-- Body Scripts -->
        <?= $this->inlineScript() ?>
    </body>
</html>
