<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?= $this->headTitle('NewDiet Care')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/jqGrid/grid.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Head Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('scripts/jquery.jqGrid.js'))
            ->prependFile($this->basePath('scripts/jquery.js'))
        ?>
    </head>
    <body>
        <div id="container">
			<div id="header">
				<div id="logo">
					<h1>NewDiet Care</h1>
				</div>
				<div id="info">
				</div>
			</div>
        	<div id="menu">
				<?php
					$menu = $this->navigation('Zend\Navigation\Default')->menu()->setUlClass('')->setLiActiveClass('selected');
					if ( ! isset( $this->location ) ) {
						$menu->findOneBy( 'label', 'Klant' )->removePage( $menu->findOneBy( 'label', 'Afrekenen' ) );
					}
					echo $menu;
				?>
        	</div>
        	<div id="content">
            	<?= $this->content; ?>
        	</div>
        </div>
        <!-- Body Scripts -->
        <?= $this->inlineScript() ?>
    </body>
</html>
