<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?= $this->headTitle('NewDiet Care')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/jqGrid/grid.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Head Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('scripts/jquery.jqGrid.js'))
            ->prependFile($this->basePath('scripts/jquery.js'))
        ?>
    </head>
    <body>
        <div id="container">
			<div id="header">
				<div id="logo">
					<h1>NewDiet Care</h1>
				</div>
				<div id="info">
				</div>
			</div>
        	<div id="menu">
				<ul>
					<li>Klant</li>
					<ul>
						<li
							<?php
							if ($this->currentControllerName == 'Application\Controller\CustomerController' && $this->currentActionName == 'new')
								echo ' class="selected"';
							?>><a href="<?= $this->url('customer', ['action' => 'new']) ?>">Nieuwe klant</a></li>
						<li
							<?php
							if ($this->currentControllerName == 'Application\Controller\CustomerController' && $this->currentActionName == 'index')
								echo ' class="selected"';
							?>><a href="<?= $this->url('customer') ?>">Kies een klant</a></li>
						<li
							<?php
							if ($this->currentControllerName == 'Application\Controller\CustomerController' && ($this->currentActionName == 'view' || $this->currentActionName == 'contact' || $this->currentActionName == 'customer' || $this->currentActionName == 'intake' || $this->currentActionName == 'diet' || $this->currentActionName == 'medical' || $this->currentActionName == 'measurements' || $this->currentActionName == 'measurementedit' || $this->currentActionName == 'newconsult' || $this->currentActionName == 'consult'))
								echo ' class="selected"';
							?>><a href="<?= $this->url('customer', ['action' => 'view']) ?>">Profiel</a></li>
						<?php
							if (isset ( $this->location )) {
						?>
						<li
							<?php
							if ($this->currentControllerName == 'Application\Controller\CustomerController' && $this->currentActionName == 'invoice')
								echo ' class="selected"';
							?>><a href="<?= $this->url('customer', ['action' => 'invoice']) ?>">Afrekenen</a></li>
						<?php
							}
						?>
						<li
							<?php
							if ($this->currentControllerName == 'Application\Controller\CustomerController' && $this->currentActionName == 'invoices')
								echo ' class="selected"';
							?>><a href="<?= $this->url('customer', ['action' => 'invoices']) ?>">Rekeningen</a></li>
					</ul>
				</ul>
        	</div>
        	<div id="content">
            	<?= $this->content; ?>
        	</div>
        </div>
        <!-- Body Scripts -->
        <?= $this->inlineScript() ?>
    </body>
</html>
