<link rel="stylesheet"
	href="<?=$this->baseUrl?>/css/jqDatePicker/datePicker.css"
	type="text/css" />
<link rel="stylesheet"
	href="<?=$this->baseUrl?>/css/jqColorPicker/colorpicker.css"
	type="text/css" />
<link rel="stylesheet" type="text/css" media="screen"
	href="<?=$this->baseUrl?>/css/agenda.css" />
<link rel='stylesheet' type='text/css' media='screen'
	href='<?=$this->baseUrl?>/css/jqSimpleModal/basic.css' />

<script type="text/javascript" src="<?=$this->baseUrl?>/scripts/date.js"></script>
<script type="text/javascript"
	src="<?=$this->baseUrl?>/scripts/jquery.datePicker.js"></script>
<script type="text/javascript"
	src="<?=$this->baseUrl?>/scripts/jquery.simplemodal.js"></script>
<script type="text/javascript"
	src="<?=$this->baseUrl?>/scripts/jquery.colorpicker.js"></script>
<script type="text/javascript"
	src="<?=$this->baseUrl?>/scripts/agenda.js"></script>