<script type="text/javascript">
	var stopSelect=false;
	
	jQuery(document).ready(function(){
	jQuery("#list").jqGrid({
		url:'<?=$this->baseUrl?>/json/customerssearch/',
		datatype: "json",
		colModel:[
		  		{label:'Achternaam', name:'achternaam', index:'achternaam', width:160},
		  		{label:'Voornaam', name:'voornaam', index:'voornaam', width:140},
		  		{label:'Tussenvoegsel', name:'tussenvoegsel', index:'tussenvoegsel', width:185},		  		
		  		{label:'Geboortedatum', name:'geboortedatum', index:'geboortedatum', width:195},
		  		{label:'Adres', name:'thuisadres', index:'thuisadres', width:100},
		  		{label:'Woonplaats', name:'thuisplaats', index:'thuisplaats', width:160},
		  		{label:'Postcode', name:'thuispostcode', index:'thuispostcode', width:130},
		  		{label:'E-mail', name:'email', index:'email', width:100},
		  		{label:' ', width:30, sortable:false, align:"center"}
		],
		viewrecords: true,
		width: 760,
		height: "auto",
		rowNum: 10,
		pager: '#pager',
		mtype: "POST",		
		sortname: 'id',
		sortorder: "asc",
		multiselect: false,
		onSelectRow: function(ids) {
			if (!stopSelect) {
				if(ids != null)
					location.href = '<?=$this->baseUrl?>/customer/view/id/'+ids+'/';
			} else
				stopSelect=false;				
		}
	});
	});
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var voornaam = jQuery("#voornaam").val();
		var achternaam = jQuery("#achternaam").val();
		var geboortedatum = jQuery("#geboortedatum").val();
		var thuisadres = jQuery("#thuisadres").val();
		var thuisplaats = jQuery("#thuisplaats").val();
		var thuispostcode = jQuery("#thuispostcode").val();
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/customerssearch/?voornaam="+voornaam+"&achternaam="+achternaam+"&geboortedatum="+geboortedatum+"&thuisadres="+thuisadres+"&thuisplaats="+thuisplaats+"&thuispostcode="+thuispostcode,page:1
		}).trigger("reloadGrid");
	}
	
	$(function(){
		$.datepicker.setDefaults({
    		dateFormat: 'dd-mm-yy',
			yearRange: "-100:+0",
		});
		$('#geboortedatum').datepicker({changeMonth: true, changeYear: true});
		$('#reg_date_from').datepicker({changeMonth: true, changeYear: true});
		$('#reg_date_to').datepicker({changeMonth: true, changeYear: true});
	});
</script>

<h2>Klantenoverzicht</h2>

<table id="search">
	<tr class="noborder">
		<td>Voornaam:</td>
		<td><input type="text" name="voornaam" id="voornaam"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td>Achternaam:</td>
		<td><input type="text" name="achternaam" id="achternaam"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td>Geboortedatum:</td>
		<td><input type="text" name="geboortedatum" id="geboortedatum"
			onkeydown="doSearch(arguments[0]||event)"
			onchange="doSearch(arguments[0]||event)" /></td>
	</tr>
	<tr class="noborder">
		<td>Adres:</td>
		<td><input type="text" name="thuisadres" id="thuisadres"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td>Woonplaats:</td>
		<td><input type="text" name="thuisplaats" id="thuisplaats"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td>Postcode:</td>
		<td><input type="text" name="thuispostcode" id="thuispostcode"
			onkeydown="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
<br />

<table id="list" cellpadding="0" cellspacing="0"></table>
<div id="pager" style="text-align: left;"></div>

<br />
<br />

<form action="<?=$this->baseUrl?>/customer/export/" method="post">
	<table>
		<tr class="noborder">
			<td>Started in:</td>
			<td>
				<select name="reg_date_year">
					<option></option>
					<?php for( $i = date( 'Y' ); $i >= 2009; $i-- ) { ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
					<?php } ?>
				</select>
			</td>
		</tr>
		<tr class="noborder">
			<td>Started: from</td>
			<td><input type="text" name="reg_date_from" id="reg_date_from" /> to <input type="text" name="reg_date_to" id="reg_date_to" /></td>
		</tr>
		<tr class="noborder">
			<td>No measurements:</td>
			<td>
				<select name="no_measurements">
					<option></option>
					<option value="2">2 months</option>
					<option value="4">4 months</option>
					<option value="6">6 months</option>
					<option value="8">8 months</option>
					<option value="10">10 months</option>
					<option value="12">12 months</option>
				</select>
			</td>
		</tr>
		<tr class="noborder">
			<td>With birthday:</td>
			<td><input type="checkbox" name="with_birthday" /></td>
		</tr>
	</table>
	<br />
	<input type="submit" value="Export" />
</form>

<br />
<br />
