<script type="text/javascript">
	jQuery(document).ready(function(){
	jQuery("#codeToSearch").focus();
		
	jQuery("#list").jqGrid({
		url:'<?=$this->baseUrl?>/json/productssearch/type/invoice/',
		datatype: "json",
		colNames:['Code', 'Product', 'Variant', 'Inhoud', '', 'Prijs'],
		colModel:[
		  		{name:'productcode',index:'productcode', width:150},
		  		{name:'name',index:'name', width:220},
		  		{name:'category',index:'category', width:150},		  		
		  		{name:'size',index:'size', width:150},
		  		{width:20, sortable:false},		  		
		  		{name:'price',index:'price', width:70, align:"right"}
		],
		rowNum:10,
		imgpath: '<?=$this->baseUrl?>/images/jqGrid',
		mtype: "POST",		
		pager: jQuery('#pager'),
		sortname: 'id',
		viewrecords: true,
		sortorder: "asc",
		multiselect: false, 		
		width: 760,
		height: "auto",
		onSelectRow: function(ids) {
			if(ids != null)
				$.getJSON('<?=$this->baseUrl?>/json/getproductbyid/', {id: ids}, onSearchSuccess);
		
			triggers.eq(0).overlay().close();
		}
	});

	var triggers = $("button.modalInput").overlay({
	    expose: { 
	        color: '#333', 
	        loadSpeed: 200, 
	        opacity: 0.9 
	    }, 

	    onClose: function(event) { 
			$('#hLocation').show();
			$('#hEmployee').show();
			jQuery("#codeToSearch").show();
			jQuery("#codeToSearch").focus();			
	    },
	     
	    closeOnClick: false 
	});
	});
	
	/////////////////////
	// Products search //
	/////////////////////
	
	var timeoutHnd;
	 	
	function doSearch(ev){
		if(timeoutHnd)
			clearTimeout(timeoutHnd);
		timeoutHnd = setTimeout(gridReload,500);
	}
	
	function gridReload(){
		var productcode = jQuery("#productcode").val();
		var name = jQuery("#name").val();
		var category = jQuery("#category").val();
		var size = jQuery("#size").val();
		var price = jQuery("#price").val();		
		jQuery("#list").setGridParam({
			url:"<?=$this->baseUrl?>/json/productssearch/type/invoice/?productcode="+productcode+"&name="+name+"&category="+category+"&size="+size+"&price="+price,page:1
		}).trigger("reloadGrid");
	}
	
	///////////////////////////
	// Invoice functionality //
	///////////////////////////
	
	var productTimeoutHnd;
	var eProductTimeoutHnd;	
	var productCount=<?=count ( $this->invoice->getLines () )?>;
	var evenRow=<?=count ( $this->invoice->getLines () ) % 2 == 0 ? 'true' : 'false'?>;
	var discount=<?=$this->currentCustomer->discount_percent?>;

	function findProduct(){
		if(productTimeoutHnd)
			clearTimeout(productTimeoutHnd);
		productTimeoutHnd = setTimeout(getProductByCode,500);
	}
	
	function getProductByCode() {
		$.getJSON('<?=$this->baseUrl?>/json/getproductbycode/', {productcode: $('#codeToSearch').val()}, onSearchSuccess);
	}

	function onSearchSuccess(obj)	{
		var price=parseFloat(obj.price);
		
		if (obj.id)
			var s_quantity='1,0';			
		else
			var s_quantity='';			
		if (price)		
			var s_price=printFloat(price,2);
		else
			var s_price='';			
		var s_total=s_price;

		if (obj.id) {
			var newProduct=1;
			
			$("tr.invoicestring").each(function() {
				if (newProduct==1 && $('#'+this.id+'product').val()==obj.id) {
					if ($('#'+this.id+'quantity').text())		
						var q=prepareFloat($('#'+this.id+'quantity').text())+1;
					else
						var q=1;
					$('#'+this.id+'quantity').text(printFloat(q,1));
					
					if ($('#'+this.id+'price').text()) {
						var t=q*prepareFloat($('#'+this.id+'price').text());		
						$('#'+this.id+'total').text(printFloat(t,2));
					}
					
					newProduct=0;
				}
			});

			if (newProduct==1) {
				productCount++;
				var stringId='invoicestring'+productCount;
				if(evenRow)
					var newRowText='<tr class="dark invoicestring" id="'+stringId+'">';
				else
					var newRowText='<tr class="light invoicestring" id="'+stringId+'">';
				evenRow=!evenRow;
				newRowText+='<td class="left" id="'+stringId+'code">'+obj.code+'</td><td colspan="2" class="left" id="'+stringId+'name">'+obj.name+'</td><td id="'+stringId+'quantity">'+s_quantity+'</td><td class="left">&#0128;</td><td class="right" id="'+stringId+'price">'+s_price+'</td><td class="left">&#0128;</td><td class="right total" id="'+stringId+'total">'+s_total+'</td><td><input type="hidden" id="'+stringId+'product" value="'+obj.id+'" /><input type="button" value="-" onClick="decQuantity('+"'"+stringId+"'"+'); return false;" /><input type="button" value="+" onClick="incQuantity('+"'"+stringId+"'"+'); return false;" /><input type="button" class="edit" value=""  onclick="editRow('+"'"+stringId+"'"+'); return false;"><input type="button" class="delete" value="" onclick="deleteRow('+"'"+stringId+"'"+'); return false;" /></td></tr>';
				$(newRowText).insertBefore("#footer");
			}

			var totalAmount=0;
			$("td.total").each(function() {
				var total=prepareFloat(this.innerHTML);
				if (total)
					totalAmount+=total;
			});

			if (totalAmount) {
				totalAmount=prepareFloat(totalAmount.toFixed(2));
				var reduction=totalAmount*discount/100;
				reduction=prepareFloat(reduction.toFixed(2));
				var totalWithReduction=totalAmount-reduction;				

				$("#t_total").text(printFloat(totalAmount,2));
				$("#t_reduction").val(printFloat(reduction,2));
				$("#t_total_with_reduction").text(printFloat(totalWithReduction,2));
			} else {
				$("#t_total").text('');
			}

			$("#codeToSearch").val('');
			$("#codeToSearch").focus();
		}
	}

	function onSelectSuccess(obj)	{
		var price=parseFloat(obj.price);

		$("#codeToSearch").val(obj.code);
		$("#s_product").val(obj.id);
		$("#s_code").val(obj.code);
		$("#s_name").text(obj.name);
		if (obj.id)
			$("#s_quantity").val('1,0');
		else
			$("#s_quantity").val('');			
		if (price)		
			$("#s_price").val(printFloat(price,2));
		else
			$("#s_price").val('');			
		$("#s_total").val($("#s_price").val());
	}

	function onQuantityChange() {
		var quantity=prepareFloat($("#s_quantity").val());
		var price=prepareFloat($("#s_price").val());
		if (quantity&&price) {
			var total=quantity*price;
			$("#s_quantity").val(printFloat(quantity,1));
			$("#s_price").val(printFloat(price,2));
			$("#s_total").val(printFloat(total,2));
		} else {
			if (quantity)
				$("#s_quantity").val(printFloat(quantity,1));				
			$("#s_price").val('');
			$("#s_total").val('');
		}
	}

	function onPriceChange() {
		var quantity=prepareFloat($("#s_quantity").val());
		var price=prepareFloat($("#s_price").val());
		if (quantity&&price) {		
			var total=quantity*price;
			$("#s_quantity").val(printFloat(quantity,1));
			$("#s_price").val(printFloat(price,2));
			$("#s_total").val(printFloat(total,2));
		} else {
			if (price)
				$("#s_price").val(printFloat(price,2));				
			$("#s_quantity").val('');
			$("#s_total").val('');
		}
	}

	function onTotalChange() {
		var quantity=prepareFloat($("#s_quantity").val());
		var total=prepareFloat($("#s_total").val());
		if (quantity&&total) {
			var price=total/quantity;
			$("#s_quantity").val(printFloat(quantity,1));
			$("#s_price").val(printFloat(price,2));
			$("#s_total").val(printFloat(total,2));
		} else {
			if (total)
				$("#s_total").val(printFloat(total,2));				
			$("#s_quantity").val('');
			$("#s_price").val('');			
		}
	}

	function onReductionChange() {
		var totalAmount=prepareFloat($("#t_total").text());
		if (totalAmount) {
			var reduction=prepareFloat($("#t_reduction").val());
			reduction=prepareFloat(reduction.toFixed(2));			
			if (reduction)
				var totalWithReduction=totalAmount-reduction;
			else
				var totalWithReduction=totalAmount;
			$("#t_total").text(printFloat(totalAmount,2));				
			$("#t_reduction").val(printFloat(reduction,2));
			$("#t_total_with_reduction").text(printFloat(totalWithReduction,2));			
		} else {
			$("#t_reduction").val('');
			$("#t_total_with_reduction").text('');			
		}
	}

	function setQuantityTo(q) {
		if ($("#s_product").val()) {		
			$("#s_quantity").val(q);
			onQuantityChange();
		}
	}

	function addProductToInvoice() {
		if ($("#s_product").val()) {
			productCount++;
			var stringId='invoicestring'+productCount;
			if(evenRow)
				var newRowText='<tr class="dark invoicestring" id="'+stringId+'">';
			else
				var newRowText='<tr class="light invoicestring" id="'+stringId+'">';
			evenRow=!evenRow;
			newRowText+='<td class="left" id="'+stringId+'code">'+$("#s_code").val()+'</td><td colspan="2" class="left" id="'+stringId+'name">'+$("#s_name").text()+'</td><td id="'+stringId+'quantity">'+$("#s_quantity").val()+'</td><td class="left">&#0128;</td><td class="right" id="'+stringId+'price">'+$("#s_price").val()+'</td><td class="left">&#0128;</td><td class="right total" id="'+stringId+'total">'+$("#s_total").val()+'</td><td><input type="hidden" id="'+stringId+'product" value="'+$("#s_product").val()+'" /><input type="button" value="-" onClick="decQuantity('+"'"+stringId+"'"+'); return false;" /><input type="button" value="+" onClick="incQuantity('+"'"+stringId+"'"+'); return false;" /><input type="button" class="edit" value=""  onclick="editRow('+"'"+stringId+"'"+'); return false;"><input type="button" class="delete" value="" onclick="deleteRow('+"'"+stringId+"'"+'); return false;" /></td></tr>';
			$(newRowText).insertBefore("#footer");

			var totalAmount=0;
			$("td.total").each(function() {
				var total=prepareFloat(this.innerHTML);
				if (total)
					totalAmount+=total;
			});

			if (totalAmount) {
				totalAmount=prepareFloat(totalAmount.toFixed(2));
				var reduction=totalAmount*discount/100;
				reduction=prepareFloat(reduction.toFixed(2));
				var totalWithReduction=totalAmount-reduction;				

				$("#t_total").text(printFloat(totalAmount,2));
				$("#t_reduction").val(printFloat(reduction,2));
				$("#t_total_with_reduction").text(printFloat(totalWithReduction,2));
			} else {
				$("#t_total").text('');
			}
		}

		$("#codeToSearch").val('');
		$("#s_product").val('');
		$("#s_code").val('');
		$("#s_name").text('');
		$("#s_quantity").val('');
		$("#s_price").val('');			
		$("#s_total").val('');
		$("#codeToSearch").focus();
		
		jQuery("#productcode").val('');
		jQuery("#name").val('');
		jQuery("#category").val('');
		jQuery("#size").val('');
		jQuery("#price").val();
		jQuery("#list").setGridParam({
			url:'<?=$this->baseUrl?>/json/productssearch/type/invoice/'
		}).trigger("reloadGrid");
	}

	function deleteRow(rowId) {
		$("#"+rowId).remove();
		
		evenRow=true;
		$("tr.invoicestring").each(function() {
			if (evenRow) {
				this.className="dark invoicestring";
			} else {
				this.className="light invoicestring";
			}
			evenRow=!evenRow;
		});
		
		var totalAmount=0;
		$("td.total").each(function() {
			var total=prepareFloat(this.innerHTML);
			if (total)
				totalAmount+=total;
		});

		if (totalAmount) {
			totalAmount=prepareFloat(totalAmount.toFixed(2));
			var reduction=totalAmount*discount/100;
			reduction=prepareFloat(reduction.toFixed(2));
			var totalWithReduction=totalAmount-reduction;				

			$("#t_total").text(printFloat(totalAmount,2));
			$("#t_reduction").val(printFloat(reduction,2));
			$("#t_total_with_reduction").text(printFloat(totalWithReduction,2));
		} else {
			$("#t_total").text('');
		}
	}

	function editRow(rowId) {
		$("#editstring").remove();
		$("tr.invoicestring").each(function() {
			$(this).show();
		});
				
		var editRowText='<tr id="editstring"><td class="left"><input type="text" style="width: 80px;" name="code" id="e_codeToSearch" value="'+$("#"+rowId+"code").text()+'" onkeydown="eFindProduct()" /></td><td colspan="2" class="left" id="e_name">'+$("#"+rowId+"name").text()+'</td><td><input type="text" id="e_quantity" value="'+$("#"+rowId+"quantity").text()+'" style="width: 60px;" onchange="eOnQuantityChange()" /></td><td></td><td class="right"><input type="text" class="number" id="e_price" value="'+$("#"+rowId+"price").text()+'" style="width: 60px;" onchange="eOnPriceChange()" /></td><td></td><td class="right"><input type="text" class="number" id="e_total" value="'+$("#"+rowId+"total").text()+'" style="width: 60px;" onchange="eOnTotalChange()" /></td><td><input type="hidden" id="e_product" value="'+$("#"+rowId+"product").val()+'" /><input type="hidden" id="e_code" value="'+$("#"+rowId+"code").text()+'" /><input type="submit" value="OK" onclick="eOnClose('+"'"+rowId+"'"+')" /></td></tr>';
		$(editRowText).insertBefore("#"+rowId);
		$("#"+rowId).hide();		
	}

	function incQuantity(rowId) {
		if ($('#'+rowId+'quantity').text())		
			var q=prepareFloat($('#'+rowId+'quantity').text())+1;
		else
			var q=1;
		$('#'+rowId+'quantity').text(printFloat(q,1));
		
		if ($('#'+rowId+'price').text()) {
			var t=q*prepareFloat($('#'+rowId+'price').text());		
			$('#'+rowId+'total').text(printFloat(t,2));
		}

		var totalAmount=0;
		$("td.total").each(function() {
			var total=prepareFloat(this.innerHTML);
			if (total)
				totalAmount+=total;
		});

		if (totalAmount) {
			totalAmount=prepareFloat(totalAmount.toFixed(2));
			var reduction=totalAmount*discount/100;
			reduction=prepareFloat(reduction.toFixed(2));
			var totalWithReduction=totalAmount-reduction;				

			$("#t_total").text(printFloat(totalAmount,2));
			$("#t_reduction").val(printFloat(reduction,2));
			$("#t_total_with_reduction").text(printFloat(totalWithReduction,2));
		} else {
			$("#t_total").text('');
		}
	}

	function decQuantity(rowId) {
		if ($('#'+rowId+'quantity').text() && prepareFloat($('#'+rowId+'quantity').text())-1>1)		
			var q=prepareFloat($('#'+rowId+'quantity').text())-1;
		else
			var q=1;
		$('#'+rowId+'quantity').text(printFloat(q,1));
		
		if ($('#'+rowId+'price').text()) {
			var t=q*prepareFloat($('#'+rowId+'price').text());		
			$('#'+rowId+'total').text(printFloat(t,2));
		}

		var totalAmount=0;
		$("td.total").each(function() {
			var total=prepareFloat(this.innerHTML);
			if (total)
				totalAmount+=total;
		});

		if (totalAmount) {
			totalAmount=prepareFloat(totalAmount.toFixed(2));
			var reduction=totalAmount*discount/100;
			reduction=prepareFloat(reduction.toFixed(2));
			var totalWithReduction=totalAmount-reduction;				

			$("#t_total").text(printFloat(totalAmount,2));
			$("#t_reduction").val(printFloat(reduction,2));
			$("#t_total_with_reduction").text(printFloat(totalWithReduction,2));
		} else {
			$("#t_total").text('');
		}
	}
	
	function eOnClose(rowId) {
		$("#"+rowId+"product").val($("#e_product").val());		
		$("#"+rowId+"code").text($("#e_code").val());
		$("#"+rowId+"name").text($("#e_name").text());		
		$("#"+rowId+"quantity").text($("#e_quantity").val());		
		$("#"+rowId+"price").text($("#e_price").val());
		$("#"+rowId+"total").text($("#e_total").val());
		$("#"+rowId).show();
		
		$("#editstring").remove();

		var totalAmount=0;
		$("td.total").each(function() {
			var total=prepareFloat(this.innerHTML);
			if (total)
				totalAmount+=total;
		});

		if (totalAmount) {
			totalAmount=prepareFloat(totalAmount.toFixed(2));
			var reduction=totalAmount*discount/100;
			reduction=prepareFloat(reduction.toFixed(2));
			var totalWithReduction=totalAmount-reduction;				

			$("#t_total").text(printFloat(totalAmount,2));
			$("#t_reduction").val(printFloat(reduction,2));
			$("#t_total_with_reduction").text(printFloat(totalWithReduction,2));
		} else {
			$("#t_total").text('');
		}
	} 
	
	function eFindProduct(){
		if(eProductTimeoutHnd)
			clearTimeout(eProductTimeoutHnd);
		eProductTimeoutHnd = setTimeout(eGetProductByCode,500);
	}
	
	function eGetProductByCode() {
		$.getJSON('<?=$this->baseUrl?>/json/getproductbycode/', {productcode: $('#e_codeToSearch').val()}, eOnSearchSuccess);
	}

	function eOnSearchSuccess(obj)	{
		var price=parseFloat(obj.price);
		
		$("#e_product").val(obj.id);
		$("#e_code").val(obj.code);
		$("#e_name").text(obj.name);
		$("#e_quantity").val('');
		if (price)		
			$("#e_price").val(printFloat(price,2));
		else
			$("#e_price").val('');			
		$("#e_total").val('');		
	}
	
	function eOnQuantityChange() {
		var quantity=prepareFloat($("#e_quantity").val());
		var price=prepareFloat($("#e_price").val());
		if (quantity&&price) {
			var total=quantity*price;
			$("#e_quantity").val(printFloat(quantity,1));
			$("#e_price").val(printFloat(price,2));
			$("#e_total").val(printFloat(total,2));
		} else {
			if (quantity)
				$("#e_quantity").val(printFloat(quantity,1));				
			$("#e_price").val('');
			$("#e_total").val('');
		}
	}

	function eOnPriceChange() {
		var quantity=prepareFloat($("#e_quantity").val());
		var price=prepareFloat($("#e_price").val());
		if (quantity&&price) {		
			var total=quantity*price;
			$("#e_quantity").val(printFloat(quantity,1));
			$("#e_price").val(printFloat(price,2));
			$("#e_total").val(printFloat(total,2));
		} else {
			if (price)
				$("#e_price").val(printFloat(price,2));				
			$("#e_quantity").val('');
			$("#e_total").val('');
		}
	}

	function eOnTotalChange() {
		var quantity=prepareFloat($("#e_quantity").val());
		var total=prepareFloat($("#e_total").val());
		if (quantity&&total) {
			var price=total/quantity;
			$("#e_quantity").val(printFloat(quantity,1));
			$("#e_price").val(printFloat(price,2));
			$("#e_total").val(printFloat(total,2));
		} else {
			if (total)
				$("#e_total").val(printFloat(total,2));				
			$("#e_quantity").val('');
			$("#e_price").val('');			
		}
	}

	function productSearch() {
		$('#hLocation').hide();
		$('#hEmployee').hide();
		$('#productcode').val($('#codeToSearch').val());
		$('#name').val($('#nameToSearch').val());
		gridReload();
	}
	
	///////////////////////
	// Save invoice data //
	///////////////////////

	function prepareToSend(form, action) {
		i=0;
		$("tr.invoicestring").each(function() {
			rowId=$(this).attr("id");
			// Product
			inputToAdd='<input type="hidden" name="invoicebody['+i+'][product]" value="'+$("#"+rowId+"product").val()+'" />';
			$(inputToAdd).appendTo("#"+form);
			// Number
			inputToAdd='<input type="hidden" name="invoicebody['+i+'][quantity]" value="'+$("#"+rowId+"quantity").text()+'" />';
			$(inputToAdd).appendTo("#"+form);
			// Price
			inputToAdd='<input type="hidden" name="invoicebody['+i+'][price]" value="'+$("#"+rowId+"price").text()+'" />';
			$(inputToAdd).appendTo("#"+form);
			// Total price
			inputToAdd='<input type="hidden" name="invoicebody['+i+'][total]" value="'+$("#"+rowId+"total").text()+'" />';
			$(inputToAdd).appendTo("#"+form);
			i++;
		});
		
		if (i) {
			// Total amount
			inputToAdd='<input type="hidden" name="total" value="'+$("#t_total").text()+'" />';
			$(inputToAdd).appendTo("#"+form);
			// Reduction						
			inputToAdd='<input type="hidden" name="reduction" value="'+$("#t_reduction").val()+'" />';
			$(inputToAdd).appendTo("#"+form);
			// Payment method		
			if (action) {				
				inputToAdd='<input type="hidden" name="paymentmethod" value="'+action+'" />';
				$(inputToAdd).appendTo("#"+form);
			}						
					
			return true;
		} else
			return false;
	}
	
	/////////////////////////
	// Auxiliary functions //
	/////////////////////////

	function printFloat(floatValue,precision) {
		return replace('.',',',floatValue.toFixed(precision));
	}

	function prepareFloat(stringValue) {
		return parseFloat(replace(',','.',stringValue));
	}

	function replace(search, replace, subject){
		var ra = replace instanceof Array,
			sa = subject instanceof Array,
			l = (search = [].concat(search)).length,
			replace = [].concat(replace),
			i = (subject = [].concat(subject)).length;
		while(j = 0, i--)
		   while(subject[i] = subject[i].split(search[j]).join(ra ? replace[j] || "" : replace[0]), ++j < l);
		return sa ? subject : subject[0];
	}
</script>

<div class="modal" id="productSearch">
<table class="list left" width="100%">
	<tr class="noborder">
		<td>Code</td>
		<td>Product</td>
		<td>Type</td>
		<td>Size</td>
		<td>Price</td>
	</tr>
	<tr class="noborder">
		<td><input type="text" name="productcode" id="productcode"
			style="width: 100px;" onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="name" id="name"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="category" id="category"
			style="width: 100px;" onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="size" id="size" style="width: 100px;"
			onkeydown="doSearch(arguments[0]||event)" /></td>
		<td><input type="text" name="price" id="price" style="width: 80px;"
			class="number" onkeydown="doSearch(arguments[0]||event)" /></td>
	</tr>
</table>
<br />

<table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
<div id="pager" class="scroll" style="text-align: left;"></div>
</div>

<h2>Afrekenen - <?=htmlentities ( $this->currentCustomer->getName () )?></h2>

<table class="list fullwidth">
	<tr class="noborder">
		<td class="left" style="width: 90px">Code</td>
		<td class="left" style="width: 200px">Product</td>
		<td style="width: 60px"></td>
		<td style="width: 70px"></td>
		<td style="width: 20px"></td>
		<td style="width: 70px"></td>
		<td style="width: 20px"></td>
		<td style="width: 70px"></td>
		<td style="width: 90px"></td>
	</tr>
	<tr class="noborder">
		<td class="left"><input type="text" style="width: 80px;"
			name="codeToSearch" id="codeToSearch" onkeydown="findProduct()" /></td>
		<td class="left"><input type="text" name="nameToSearch"
			id="nameToSearch" style="width: 220px" /></td>
		<td class="left">
		<button
			style="margin: 0; padding: 0; border: none; width: 1px; height: 1px; position: inline"
			onfocus="this.blur();"></button>
		<button style="position: inline" class="modalInput"
			rel="#productSearch" onclick="productSearch()" onfocus="this.blur();">Zoek</button>
		</td>
		<td colspan="6"></td>
	</tr>
	<tr class="noborder">
		<td colspan="9"></td>
	</tr>
	<tr>
		<th class="left">Code</th>
		<th class="left">Product</th>
		<th></th>
		<th>Aantal</th>
		<th colspan="2" class="left">Prijs&nbsp;p/st</th>
		<th colspan="2" class="left">Prijs</th>
		<th>Bewerken</th>
	</tr>

	<?php
	$productCount = 1;
	$evenRow = true;
	if (count ( $this->invoice->getLines () ) > 0) {
		foreach ( $this->invoice->getLines () as $line ) {
			$stringId = 'invoicestring' . $productCount;
			?>
	<tr class="<?=$evenRow ? 'dark' : 'light'?> invoicestring"
		id="<?=$stringId?>">
		<td class="left" id="<?=$stringId?>code"><?=htmlentities ( $line->getProduct ()->productcode )?></td>
		<td colspan="2" class="left" id="<?=$stringId?>name"><?=$this->escape ( $line->getProduct ()->name )?></td>
		<td id="<?=$stringId?>quantity"><?=$this->printFloat->filter ( $line->number )?></td>
		<td class="left">&#0128;</td>
		<td class="right" id="<?=$stringId?>price"><?=$this->printPrice->filter ( $line->number != 0 ? $line->total_price / $line->number : 0 )?></td>
		<td class="left">&#0128;</td>
		<td class="right total" id="<?=$stringId?>total"><?=$this->printPrice->filter ( $line->total_price )?></td>
		<td><input type="hidden" id="<?=$stringId?>product"
			value="<?=$line->getProduct ()->id?>" /><input type="button"
			value="-" onClick="decQuantity('<?=$stringId?>'); return false;" /><input
			type="button" value="+"
			onClick="incQuantity('<?=$stringId?>'); return false;" /><input
			type="button" class="edit" value=""
			onclick="editRow('<?=$stringId?>'); return false;"><input
			type="button" class="delete" value=""
			onclick="deleteRow('<?=$stringId?>'); return false;" /></td>
	</tr>
			<?php
			$productCount ++;
			$evenRow = ! $evenRow;
		}
	}
	?>

	<tr class="noborder" id="footer">
		<td class="left"><b>Totaal</b></td>
		<td class="left"></td>
		<td></td>
		<td></td>
		<td class="left"></td>
		<td></td>
		<td class="left">&#0128;</td>
		<td class="right" id="t_total" style="font-weight: bold"><?=$this->printPrice->filter ( $this->invoice->total )?></td>
		<td></td>
	</tr>
	<tr class="noborder">
		<td class="left"><b>Korting</b></td>
		<td class="left"></td>
		<td></td>
		<td></td>
		<td class="left"></td>
		<td></td>
		<td class="left">&#0128;</td>
		<td class="right" style="font-weight: bold"><input type="text"
			class="number" id="t_reduction"
			value="<?=$this->printPrice->filter ( $this->invoice->reduction )?>"
			style="width: 60px;" onchange="onReductionChange();" /></td>
		<td></td>
	</tr>
	<tr class="noborder">
		<td class="left" colspan="2"><b>Totaal inclusief Korting</b></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td class="left">&#0128;</td>
		<td class="right" id="t_total_with_reduction"
			style="font-weight: bold"><?=$this->printPrice->filter ( $this->invoice->total - $this->invoice->reduction )?></td>
		<td></td>
	</tr>
	<tr class="noborder">
		<td colspan="9"></td>
	</tr>
</table>
<br />
<span>
<form id="sendForm1"
	action="<?=$this->baseUrl?>/customer/invoice/<?=$this->invoice->id ? 'id/' . $this->invoice->id . '/' : ''?>"
	method="post"><input type="submit" value="Contant"
	onclick="return prepareToSend('sendForm1', 'cash')" /> <input
	type="submit" value="PIN"
	onclick="return prepareToSend('sendForm1', 'pin')" /> <input
	type="submit" value="Op rekening"
	onclick="return prepareToSend('sendForm1', 'credit')" /></form>
</span>
<span>
<form id="sendForm2"
	action="<?=$this->baseUrl?>/customer/invoice/<?=$this->invoice->id ? 'id/' . $this->invoice->id . '/' : ''?>"
	method="post"><input type="submit" value="Bewaar"
	onclick="return prepareToSend('sendForm2', '')" /></form>
<?php
if ($this->invoice->status == 'open' && $this->invoice->id) {
	?>
<form method="post"
	action="<?=$this->baseUrl?>/customer/invoicedel/id/<?=$this->invoice->id?>/"
	onsubmit="return confirm('Verwijder deze rekening?')"><input
	type="submit" value="Verwijder" /></form>
<?php
}
?>
</span>
<br />
<br />
