<link rel="stylesheet" type="text/css" media="screen"
	href="<?=$this->baseUrl?>/css/jqGrid/jqModal.css" />

<script src="<?=$this->baseUrl?>/scripts/js/jqModal.js"
	type="text/javascript"></script>
<script src="<?=$this->baseUrl?>/scripts/js/jqDnR.js"
	type="text/javascript"></script>
<script type="text/javascript"
	src="<?=$this->baseUrl?>/scripts/jquery.tools.js"></script>

<style>
#content {
	position: static;
}
</style>
